#服务器端口
server:
  port: 8106

#数据源配置
spring:
  datasource:
    url: ${beletech.datasource.test.url}
    username: ${beletech.datasource.test.username}
    password: ${beletech.datasource.test.password}
