knife4j:
  cloud:
    routes:
      - name: 授权模块
        uri: 127.0.0.1
        location: /beletech-auth/v2/api-docs
      - name: 工作台模块
        uri: 127.0.0.1
        location: /beletech-desk/v2/api-docs
      - name: 系统模块
        uri: 127.0.0.1
        location: /beletech-system/v2/api-docs
