knife4j:
  cloud:
    routes:
      - name: 授权模块
#        uri: 192.168.0.157:88
        location: /beletech-auth/v2/api-docs
      - name: 工作台模块
#        uri: 192.168.0.157:88
        location: /beletech-desk/v2/api-docs
      - name: 系统模块
#        uri: 192.168.0.157:88
        location: /beletech-system/v2/api-docs
